git:
  depth: 3
language: node_js
node_js: stable
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- export NODE_ENV=test
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app:
    master: angular-full-seed
  api_key:
    secure: uOHQWu7Z8uaijGRk28liDxsl3JvjKMMg3YpFXZz7gQIdhgJ7mOKbluodadKKI2BnhIaztd6Wr/PW6RwGWEzmEuh1ZfI1uNY0OmZe4LKK3YRhMEM38Xi+ahAuc51mtE+XfoXuoWdoFQ02G1VU8fKT1k8u1xwme06PbXaAfblGJDHECqaVhAePPMeXU14Paj5eLE6A4aaoTyj8Pyxsno9y6+W3DUaXtwDXuJh9nKt3y/XQA7F6GyC6p4sCPwFma3kfGBlJQY0gXHdBDzyX01llDkpqgvt83AG8t57349XG6YexHOP9mRWMLHi3o5AR4lZLQ2UGt4HOcEATE9qudSPD7O3qbnrUsxSSonlbBQbZklsQi2itf0Dho/s/EzMhJAmUOjvMqe7pBdYjtzgIjolTEA7kHIx/K3wVYpZhFmU5C7rWGhWFEtQB7vphSu7d7x5pG17+jVpT444kEU71Cykk/wy3ImlRD/SsJWT69MoyepxORRXgmb/TX88/qbB5TXTXCMCYkWvdv5vtB93AlQE3XS1UcAtJ1vNUCzWhwEYJHkF0ux/F6f8MfyU9QHcp9zo3l71ndKWw53AUNjr9Rw3drN/bFkP+5TqHpFvbHVRAH76j6XhNgaMO2WynbwQuUvmHLaxPNj7cu6QrA5oCuVMlxtbB7jTFhpycanBpeAN9pys=
